---
id: Core
name: Core
full: Core Horde Framework library
description: >-
  A library that provides the core functionality of the Horde Application
  Framework.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Core
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: developer
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: developer
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/alarm: ^3
      horde/auth: ^3
      horde/autoloader: ^3
      horde/browser: ^3
      horde/cache: ^3
      horde/cli: ^3
      horde/compress: ^3
      horde/compress_fast: ^2
      horde/controller: ^3
      horde/cssminify: ^2
      horde/data: ^3
      horde/date: ^3
      horde/exception: ^3
      horde/group: ^3
      horde/hashtable: ^2
      horde/history: ^3
      horde/injector: ^3
      horde/javascriptminify: ^2
      horde/lock: ^3
      horde/log: ^3
      horde/logintasks: ^3
      horde/mime: ^3
      horde/mime_viewer: ^3
      horde/notification: ^3
      horde/pack: ^2
      horde/perms: ^3
      horde/prefs: ^3
      horde/secret: ^3
      horde/serialize: ^3
      horde/sessionhandler: ^3
      horde/share: ^3
      horde/support: ^3
      horde/template: ^3
      horde/token: ^3
      horde/text_filter: ^3
      horde/translation: ^3
      horde/url: ^3
      horde/util: ^3
      horde/view: ^3
      pear/pear: '*'
    ext:
      session: '*'
  optional:
    composer:
      horde/activeSync: ^3
      horde/backup: ^2
      horde/crypt: ^2
      horde/dav: ^2
      horde/db: ^3
      horde/editor: ^3
      horde/elasticsearch: ^2
      horde/form: ^3
      horde/http: ^3
      horde/icalendar: ^3
      horde/image: ^3
      horde/imap_client: ^3
      horde/javascriptminify_jsmin: ^2
      horde/kolab_server: ^3
      horde/kolab_session: ^3
      horde/kolab_storage: ^3
      horde/ldap: ^3
      horde/mail: ^3
      horde/mongo: ^2
      horde/nls: ^3
      horde/oauth: ^3
      horde/queue: ^2
      horde/routes: ^3
      horde/service_twitter: ^3
      horde/spellchecker: ^3
      horde/test: ^3
      horde/tree: ^3
      horde/vfs: ^3
      pear/net_dns2: ^1.5
      pear/text_languagedetect: '*'
    pear:
      pear.php.net/Text_CAPTCHA: '*'
      pear.php.net/Text_Figlet: '*'
    ext:
      dom: '*'
      hash: '*'
      SimpleXML: '*'
      sockets: '*'
autoload:
  classmap:
    - lib/
    - src/
